defaults: &defaults
  
  identity_provider_base_url: 'https://localhost/identity_provider'
  client_base_url: 'https://localhost/client'
  
  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'
  
development:
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults

  identity_provider_base_url: 'https://test1.wack-a-doo.de/identity_provider'
  client_base_url: 'https://test1.wack-a-doo.de/client'

  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'

  

production:
  <<: *defaults

  identity_provider_base_url: 'https://wack-a-doo.de/identity_provider'
  client_base_url: 'https://localhost/client'

  client_id:       'WACKADOOHTML5-ROUND2'
  client_password: 'wacky2'
