defaults: &defaults
  
  identity_provider_path:  '/identity_provider'
  client_base_url:         '/client'

  client_id:               'WACKADOOHTML5'
  client_password:         'wacky'
  
  requested_scopes:        'payment 5dentity wackadoo'
  
  ingame_news_url:         '/game_server/fundamental/announcements?language=all'

  base_url: 'https://www.wack-a-doo.com'

  domains_with_locale:
    'wack-a-doo.de':         de
    'wack-a-doo.com':        en
    'test1.wack-a-doo.de':   de
    'test1.wack-a-doo.com':  en

development:
  <<: *defaults
  
  ingame_news_url:         'https://gs02.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  domains_with_locale:
    'localhost':  de
    'testdomain': en

test:
  <<: *defaults

staging:
  <<: *defaults

  client_base_url:         'https://test1.wack-a-doo.com/client'

  client_id:               'WACKADOO-HTML5-TEST'
  client_password:         'htmlwad-test'
  requested_scopes:        'payment 5dentity wackadoo-testround3'

  ingame_news_url:         '/game_server/fundamental/announcements?language=all'

  base_url: 'https://test1.wack-a-doo.com'

  domains_with_locale:
    'test1.wack-a-doo.de':  de
    'test1.wack-a-doo.com': en

production:
  <<: *defaults

  client_base_url:         'https://gs09.wack-a-doo.com/client'

  client_id:               'WACKADOO-HTML5'   # this must be also created in the identity provider to assign correct scopes to users
  client_password:         'htmlwad'
  requested_scopes:        'payment 5dentity wackadoo-round9'
  
  ingame_news_url:         'https://gs09.wack-a-doo.de/game_server/fundamental/announcements?language=all'


staging_test:
  <<: *defaults

  client_base_url:         'https://staging-test.wack-a-doo.de/client'

  client_id:               'WACKADOOHTML5'
  client_password:         'wacky'

  ingame_news_url:         'https://staging-test.wack-a-doo.de/game_server/fundamental/announcements?language=all'