defaults: &defaults
  
  identity_provider_base_url: 'https://localhost/identity_provider'
  client_base_url: 'https://localhost/client'
  
  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'
  
  requested_scopes: 'payment 5dentity wackadoo'
  
  ingame_news_url:  'https://localhost/game_server/fundamental/announcements?language=all'
  
  redirector_url:   'http://localhost/identity_provider/redirect_to'

  
development:
  <<: *defaults
  
  ingame_news_url:  'https://gs02.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  
test:
  <<: *defaults

staging:
  <<: *defaults

  identity_provider_base_url: 'https://test1.wack-a-doo.de/identity_provider'
  client_base_url: 'https://test1.wack-a-doo.de/client'

  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'

  ingame_news_url:  'https://test1.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  redirector_url:   'http://test1.wack-a-doo.de/identity_provider/redirect_to'

  

production:
  <<: *defaults

  identity_provider_base_url: 'https://wack-a-doo.de/identity_provider'
  client_base_url:  'https://gs02.wack-a-doo.de/client'

  client_id:        'WACKADOOHTML5-ROUND2'   # this must be also created in the identity provider to assign correct scopes to users
  client_password:  'wacky2'
  requested_scopes: 'payment 5dentity wackadoo-round2'
  
  ingame_news_url:  'https://gs02.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  redirector_url:   'http://wack-a-doo.de/identity_provider/redirect_to'


staging:
  <<: *defaults

  identity_provider_base_url: 'https://staging-test.wack-a-doo.de/identity_provider'
  client_base_url: 'https://staging-test.wack-a-doo.de/client'

  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'

  ingame_news_url:  'https://staging-test.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  redirector_url:   'http://staging-test.wack-a-doo.de/identity_provider/redirect_to'



