defaults: &defaults
  
  identity_provider_base_url: '/identity_provider'
  client_base_url: '/client'
  
  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'
  
  requested_scopes: 'payment 5dentity wackadoo'
  
  ingame_news_url:  '/game_server/fundamental/announcements?language=all'
  
  redirector_url:   'http://testdomain/identity_provider/redirect_to'

  domains_with_locale:
    'wack-a-doo.de':  de
    'wack-a-doo.com': en
  
development:
  <<: *defaults
  
  ingame_news_url:  'https://gs02.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  domains_with_locale:
    'localhost':  de
    'testdomain': en

test:
  <<: *defaults

staging:
  <<: *defaults

  identity_provider_base_url: 'https://test1.wack-a-doo.de/identity_provider'
  client_base_url: 'https://test1.wack-a-doo.de/client'

  client_id:        'WACKADOOHTML5-TESTROUND2'
  client_password:  'wackytest2'
  requested_scopes: 'payment 5dentity wackadoo-testround2'

  ingame_news_url:  'https://test1.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  redirector_url:   'http://test1.wack-a-doo.de/identity_provider/redirect_to'

  domains_with_locale:
    'test1.wack-a-doo.de':  de
    'test1.wack-a-doo.com': en

production:
  <<: *defaults

  identity_provider_base_url: 'https://wack-a-doo.de/identity_provider'
  client_base_url:  'https://gs02.wack-a-doo.de/client'

  client_id:        'WACKADOOHTML5-ROUND2'   # this must be also created in the identity provider to assign correct scopes to users
  client_password:  'wacky2'
  requested_scopes: 'payment 5dentity wackadoo-round2'
  
  ingame_news_url:  'https://gs02.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  redirector_url:   'http://wack-a-doo.de/identity_provider/redirect_to'


staging_test:
  <<: *defaults

  identity_provider_base_url: 'https://staging-test.wack-a-doo.de/identity_provider'
  client_base_url: 'https://staging-test.wack-a-doo.de/client'

  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'

  ingame_news_url:  'https://staging-test.wack-a-doo.de/game_server/fundamental/announcements?language=all'

  redirector_url:   'http://staging-test.wack-a-doo.de/identity_provider/redirect_to'



