defaults: &defaults
  
  identity_provider_base_url: 'https://wack-a-doo.de/identity_provider'
  
  client_id:       'WACKADOOHTML5'
  client_password: 'wacky'
  
development:
  <<: *defaults

  identity_provider_base_url: 'https://localhost/identity_provider'
  
test:
  <<: *defaults

testing:
  <<: *defaults

  identity_provider_base_url: 'https://test1.wack-a-doo.de/identity_provider'
  

production:
  <<: *defaults
