---
pid: /var/run/portal_staging_test.pid
timeout: 30
wait: 30
log: log/thin/portal_staging_test.log
max_conns: 1024
require: []

environment: staging_test
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/www/portal_staging_test/current
socket: /var/run/portal_staging_test.sock