---
pid: /var/run/portal_testround2.pid
timeout: 30
wait: 30
log: log/thin/portal_testround2.log
max_conns: 1024
require: []

environment: testround2
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /var/www/portal_testround2/current
socket: /var/run/portal_testround2.sock