---
pid: /var/run/portal/portal.pid
timeout: 30
wait: 30
log: log/thin/portal.log
max_conns: 1024
require: []

environment: staging
max_persistent_conns: 512
servers: 3
daemonize: true
chdir: /var/www/portal/current
socket: /var/run/portal/portal.sock